# Generated by Django 3.0.2 on 2020-03-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_data_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='username',
        ),
    ]
